MoneyTransfer/Controllers/BankController.cs
using Microsoft.AspNetCore.Mvc;

namespace MoneyTransfer.Controllers
{
    public class BankController : Controller
    {
        public IActionResult Registration()
        {

            return View();
        }
        public IActionResult Login()
        {
            return View();
        }


        //Agent sub field view
        public IActionResult Agent()
        {
            return View();
        }
        public IActionResult Nepalagentlist()
        {
            return View();
        }
        public IActionResult Abroadagentlist()
        {
            return View();
        }
        //


        public IActionResult Currenttransaction()
        {
            return View();
        }
        public IActionResult Newtransaction()
        {
            return View();
        }
        public IActionResult Nepalagent()
        {
            return View();
        }
        public IActionResult Abroadagent()
        {
            return View();
        }

        public IActionResult Homepage()
        {
            return View();
        }

    }
}

MoneyTransfer/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MoneyTransfer.Models;

namespace MoneyTransfer.Controllers
{
    public class MessagesController : Controller
    {
        private readonly TransferOfficialContext _context;

        public MessagesController(TransferOfficialContext context)
        {
            _context = context;
        }

        // GET: Messages
        public async Task<IActionResult> Index()
        {
              return _context.Messages != null ? 
                          View(await _context.Messages.ToListAsync()) :
                          Problem("Entity set 'TransferOfficialContext.Messages'  is null.");
        }

        // GET: Messages/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Messages == null)
            {
                return NotFound();
            }

            var message = await _context.Messages
                .FirstOrDefaultAsync(m => m.Id == id);
            if (message == null)
            {
                return NotFound();
            }

            return View(message);
        }

        // GET: Messages/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Messages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Bank,Amount,Date,DocumentPath")] Message message)
        {
            if (ModelState.IsValid)
            {
                _context.Add(message);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(message);
        }

        // GET: Messages/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Messages == null)
            {
                return NotFound();
            }

            var message = await _context.Messages.FindAsync(id);
            if (message == null)
            {
                return NotFound();
            }
            return View(message);
        }

        // POST: Messages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Bank,Amount,Date,DocumentPath")] Message message)
        {
            if (id != message.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(message);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MessageExists(message.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(message);
        }

        // GET: Messages/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Messages == null)
            {
                return NotFound();
            }

            var message = await _context.Messages
                .FirstOrDefaultAsync(m => m.Id == id);
            if (message == null)
            {
                return NotFound();
            }

            return View(message);
        }

        // POST: Messages/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Messages == null)
            {
                return Problem("Entity set 'TransferOfficialContext.Messages'  is null.");
            }
            var message = await _context.Messages.FindAsync(id);
            if (message != null)
            {
                _context.Messages.Remove(message);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MessageExists(int id)
        {
          return (_context.Messages?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

MoneyTransfer/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MoneyTransfer.Models;

namespace MoneyTransfer.Controllers
{
    public class RolesController : Controller
    {
        private readonly TransferOfficialContext _context;

        public RolesController(TransferOfficialContext context)
        {
            _context = context;
        }

        // GET: Roles
        public async Task<IActionResult> Index()
        {
              return _context.Roles != null ? 
                          View(await _context.Roles.ToListAsync()) :
                          Problem("Entity set 'TransferOfficialContext.Roles'  is null.");
        }

        // GET: Roles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Roles == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // GET: Roles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Roles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Role1")] Role role)
        {
            if (ModelState.IsValid)
            {
                _context.Add(role);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Roles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Roles == null)
            {
                return NotFound();
            }

            var role = await _context.Roles.FindAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        // POST: Roles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Role1")] Role role)
        {
            if (id != role.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(role);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoleExists(role.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Roles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Roles == null)
            {
                return NotFound();
            }

            var role = await _context.Roles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Roles == null)
            {
                return Problem("Entity set 'TransferOfficialContext.Roles'  is null.");
            }
            var role = await _context.Roles.FindAsync(id);
            if (role != null)
            {
                _context.Roles.Remove(role);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RoleExists(int id)
        {
          return (_context.Roles?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

MoneyTransfer/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MoneyTransfer.Models;

namespace MoneyTransfer.Controllers
{
    public class UsersController : Controller
    {
        private readonly TransferOfficialContext _context;

        public UsersController(TransferOfficialContext context)
        {
            _context = context;
        }

        // GET: Users
        public async Task<IActionResult> Index()
        {
            var transferOfficialContext = _context.Users.Include(u => u.Role);
            return View(await transferOfficialContext.ToListAsync());
        }
        // Registration of user
        public ActionResult Registration(String Name,String Address,String Phone)
        {
            User obj = new User();
            obj.Name = Name;
            obj.Address = Address;
            obj.Phone = Phone;
            _context.Add(obj);
            _context.SaveChanges();

            return RedirectToAction("Login", "Bank");
        }

        // GET: Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .Include(u => u.Role)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Create
        public IActionResult Create()
        {
            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Id");
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Address,Phone,Status,RoleId")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Id", user.RoleId);
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Id", user.RoleId);
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Address,Phone,Status,RoleId")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["RoleId"] = new SelectList(_context.Roles, "Id", "Id", user.RoleId);
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Users == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .Include(u => u.Role)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Users == null)
            {
                return Problem("Entity set 'TransferOfficialContext.Users'  is null.");
            }
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
          return (_context.Users?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

MoneyTransfer/Views/Bank/Login.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


   <div>
    
  <!-- Navbar sm -->
  <div class="  d-lg-none d-md-none d-sm-block d-block bg-nav ">
      <div class="d-flex justify-content-between"> 

    <div class="d-flex ">
      <a class="py-3 left  bg-active ancor" href="index.html"> <i
          class="  mx-3  fa-solid fa-house-chimney-window  mt-1 "></i></a>
      <a class="py-3 left  ancor" href="our_service.html"> <i class="fa-solid  mx-3   fa-camera-retro  mt-1 "></i></a>
     @* <a class="py-3 left  ancor" href="Gallary.html"> <i class="fa-solid  mx-3  fa-handshake   mt-1 "></i></a> *@
      <a class="py-3 left  ancor" href="Aboutus.html"><i class="fa-solid   mx-3  fa-id-card-clip  mt-1 "></i></a>
      <a class="py-3 left  ancor" href="#"><i class="fa-solid   mx-3   fa-address-book mt-1 "></i></a>
    </div>
    <div class="mt-3 mr-2"><a href="Registration">Signup</a></div>
    </div>
 
  </div>
  <!-- Navbar lg md -->
  <div class="flex w-100 p-0 ">
    
    <div class="p-0 bg-nav col-lg-2 col-md-3 d-lg-block d-md-block d-none position-fixed " style="height:100%;">
       
      <div class="d-flex flex-column justify-content-lg-around center " >
        <!-- logo -->

        
               <img class="logosection  mb-md-2 mt-3 " src="https://images.pexels.com/photos/757185/pexels-photo-757185.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
          width="80" alt="" srcset="">
      
     
        <!-- Tag -->
        <div>
            <a class="py-3 bg-active ancor w-100" href="index.html">
              <div class="d-flex  position-relative "><i class="fa-solid fa-house-chimney-window px-2 mt-1 "></i>
                <p class="mt-0 mb-0 margin">Home</p>
              </div>
            </a>
            <a class="py-3  ancor w-100" asp-controller="BankDetails" asp-action="Index" >
              <div class="d-flex  position-relative "><i class="fas fa-handshake fa-solid  px-2 mt-1"></i>
                <p class="mt-0 mb-0 margin">BankDetails</p>
              </div>
            </a>
         
            <a class="py-3  ancor w-100" asp-controller="Transactions" asp-action="Index">
              <div class="d-flex  position-relative "><i class="fa-solid  fa-id-card-clip px-2 mt-1 "></i>
                <p class="mt-0 mb-0 margin">Transaction</p>
              </div>
            </a>
            <a class="py-3  ancor w-100" asp-controller="Messages" asp-action="Index">
              <div class="d-flex  position-relative "><i class="fa-solid   fa-address-book px-2 mt-1 "></i>
                <p class="mt-0 mb-0 margin">Message</p>
              </div>
            </a>
             <a class="py-3  ancor w-100" asp-controller="Roles" asp-action="Index">
              <div class="d-flex  position-relative "><i class="fa-solid   fa-address-book px-2 mt-1 "></i>
                <p class="mt-0 mb-0 margin">Role</p>
              </div>
            </a>
            <a class="py-3  ancor w-100" asp-controller="Users" asp-action="Index">
              <div class="d-flex  position-relative "><i class="fa-solid   fa-address-book px-2 mt-1 "></i>
                <p class="mt-0 mb-0 margin">Uers</p>
              </div>
            </a>

        </div>
        @*3rd row *@

        <div><a href="Registration">Signup</a>
        </div>

      </div>
    </div>

    <!-- Main section-->

   


      <!-- !0    one flex text -->

            
    <div class=" d-flex flex-row-reverse overflow-hidden  p-0"  style="height:760px;">
        <div class="col-lg-10 col-md-9 bg-body">
            


     <div class="  d-flex row p-0 " >
  <!--  <div class=" d-sm-none d-lg-block d-none col-lg-3 background bg-dark " >

    </div> -->
    <div class=" col-lg-12 col-sm-12 mt-5  ">

      
      <!-- Login form -->

  
      <div class=" d-flex col-sm-12 col-md-8 col-lg-6 mt-5 container-fluid ">
       
        <form class="row g-3 py-5 px-4 bg-nav  shadow-lg " style="border-radius:9px;">
        <div class="text-center w-100 mb-5 "><h1 class=" text-forth-color" >Login</h1></div>  

        
          <div class="w-100  mt-2 p-0">
            <div class="d-flex flex-col">
              @*<label for="Name" class="form-label mx-2 mt-1 ">Name:</label>*@
              <input type="text" class="form-control " id="Name" placeholder="Email Address">
            </div>
          </div>

         
          <div class="w-100 mt-3 p-0">
             <div class="d-flex flex-col ">
          @*  <label for="Password" class="mx-2 mt-1 ">Password:</label> *@
            <input type="password" class="form-control" id="password" placeholder="Password">
          </div>       
          </div>

       
        <div class="d-flex justify-content-between w-100 mt-3 ">
             <div class="form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Remember me</label>
                </div>

                <div>
                       <a href="" class=" mt-3 "><span>Forgot password ?</span></a>
                </div>

          
        </div>
         <div class="w-100" > <button type="submit" class="custombtn px-3 mt-2 ">Login</button></div>

          <a href="Registration" class="  mt-3">Sign up</a>
         
        </form>

        
      </div>

    </div>

  </div>


      </div>
    </div>


    
    
      <!-- <hr class="featurette-divider"> -->
 


    </div>

  </div>
    

MoneyTransfer/Views/Bank/Registration.cshtml
   @*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


   <div>
    
  <!-- Navbar sm -->
  <div class="  d-lg-none d-md-none d-sm-block d-block bg-nav ">
      <div class="d-flex justify-content-between"> 

    <div class="d-flex ">
      <a class="py-3 left  bg-active ancor" href="index.html"> <i
          class="  mx-3  fa-solid fa-house-chimney-window  mt-1 "></i></a>
      <a class="py-3 left  ancor" href="our_service.html"> <i class="fa-solid  mx-3   fa-camera-retro  fa-handshake   mt-1 "></i></a>
     @* <a class="py-3 left  ancor" href="Gallary.html"> <i class="fa-solid  mx-3  fa-camera-retro   mt-1 "></i></a> *@
      <a class="py-3 left  ancor" href="Aboutus.html"><i class="fa-solid   mx-3  fa-id-card-clip  mt-1 "></i></a>
      <a class="py-3 left  ancor" href="#"><i class="fa-solid   mx-3   fa-address-book mt-1 "></i></a>
    </div>
    <div class="mt-3 mr-2"><a href="Login">Login</a></div>
    </div>
 
  </div>
  <!-- Navbar lg md -->
  <div class="flex w-100 p-0 ">
    
    <div class="p-0 bg-nav col-lg-2 col-md-3 d-lg-block d-md-block d-none position-fixed " style="height:100%;">
       
      <div class="d-flex flex-column justify-content-lg-around center " >
        <!-- logo -->

        
               <img class="logosection  mb-md-2 mt-3" src="https://images.pexels.com/photos/757185/pexels-photo-757185.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
          width="80" alt="" srcset="">
      
     
        <!-- Tag -->
        <div>
            <a class="py-3 bg-active ancor w-100" href="index.html">
              <div class="d-flex  position-relative "><i class="fa-solid fa-house-chimney-window px-2 mt-1 "></i>
                <p class="mt-0 mb-0 margin">Home</p>
              </div>
            </a>
            <a class="py-3  ancor w-100" asp-controller="BankDetails" asp-action="Index" >
              <div class="d-flex  position-relative "><i class="fas fa-handshake fa-solid  px-2 mt-1"></i>
                <p class="mt-0 mb-0 margin">BankDetails</p>
              </div>
            </a>
         
            <a class="py-3  ancor w-100" asp-controller="Transactions" asp-action="Index">
              <div class="d-flex  position-relative "><i class="fa-solid  fa-id-card-clip px-2 mt-1 "></i>
                <p class="mt-0 mb-0 margin">Transaction</p>
              </div>
            </a>
            <a class="py-3  ancor w-100" asp-controller="Messages" asp-action="Index">
              <div class="d-flex  position-relative "><i class="fa-solid   fa-address-book px-2 mt-1 "></i>
                <p class="mt-0 mb-0 margin">Message</p>
              </div>
            </a>
             <a class="py-3  ancor w-100" asp-controller="Roles" asp-action="Index">
              <div class="d-flex  position-relative "><i class="fa-solid   fa-address-book px-2 mt-1 "></i>
                <p class="mt-0 mb-0 margin">Role</p>
              </div>
            </a>
            <a class="py-3  ancor w-100" asp-controller="Users" asp-action="Index">
              <div class="d-flex  position-relative "><i class="fa-solid   fa-address-book px-2 mt-1 "></i>
                <p class="mt-0 mb-0 margin">Uers</p>
              </div>
            </a>

        </div>
        @*3rd row *@

        <div><a href="Login">Login</a>
        </div>

      </div>
    </div>

    <!-- Main section-->

   


      <!-- !0    one flex text -->

            
    <div class=" d-flex flex-row-reverse overflow-hidden  p-0  " style="height:760px; ">
        <div class="col-lg-10 col-md-9 bg-body ">
            


     <div class="  d-flex row " >
  <!--  <div class=" d-sm-none d-lg-block d-none col-lg-3 background bg-dark " >

    </div> -->
    <div class=" col-lg-12 col-sm-12 mt-2 ">

      
      <!--Registration form -->

  
      <div class=" d-flex col-sm-12 col-md-8 col-lg-6  container-fluid   ">
       
        <form class="row g-3 py-5 px-4 bg-nav shadow-lg" style="border-radius:9px;" method="post" asp-controller="Users" asp-action="Registration">
        <div class="text-center w-100 mb-5 "><h1 class=" text-forth-color" >Registration</h1></div>  

        <div class="d-flex flex-sm-row w-100">
              <div class="col-md-6  mt-3   col-sm-6 p-0">
              <label class="ml-2"> Nepal_Agent
                <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" class="ml-2 "  checked>
              </label>  
          </div>

    
          <div class="col-md-6 mt-3 col-sm-6 p-0">
            <label class="ml-2"> Abroad_Agent
              <input type="radio" name="optionsRadios" id="optionsRadios1" value="option1" class="ml-2"  >
            </label>
          </div>

        </div>
        
            


         

          <div class="col-md-12  mt-2 p-0">
            <div class="d-flex flex-col">
             @* <label for="Name" class="form-label mx-2 mt-1 ">Name:</label> *@
              <input type="text" class="form-control h-75 " id="Name" name="Name" placeholder=" Name">
            </div>
          </div>

          <div class="col-md-12  mt-3 p-0">
            <div class="d-flex flex-col">
            @*  <label for="Address" class="form-label mx-2 mt-1 ">Address:</label>*@
              <input type="text" class="form-control " id="Address" name="Address" placeholder="Address" />
            </div>
          </div>



          <div class="col-md-12  mt-3 p-0">
            <div class="d-flex flex-col">
             @* <label for="Phone" class="form-label mx-2 mt-1 ">Phone:</label> *@
              <input type="text" class="form-control " id="Phone" name="Phone" placeholder="Phone">
            </div>
          </div>

        <!-- <div class="col-md-6 mt-3 p-0">
            <div class="d-flex flex-col">
             @* <label for="phone" class="form-label mx-2 mt-1 ">Phone_1:</label>*@
              <input type="email" class="form-control " id="phone" placeholder="phone_no">
            </div>
          </div>-->
           
      <!--    <div class="col-md-5 mt-3 p-0 ml-lg-2 ml-md-2 ">
            <div class="d-flex flex-col">
            @*  <label for="phone2" class="form-label mx-2 mt-1 ">phone_2:</label>*@
              <input type="email" class="form-control " id="phone2" placeholder="Phone_no 2">
            </div>
          </div> -->

      <!--    <div class="col-md-12 mt-3 p-0">
            <div class="d-flex flex-col">
             @* <label for="inputEmail" class="form-label mx-2 mt-1 ">Email_Address:</label>*@
              <input type="email" class=" a form-control " id="inputEmail" placeholder=" Email">
            </div>
          </div> -->

        <div class="col-md-12 mt-3 p-0">
             <div class="d-flex flex-col ">
          @*  <label for="Password" class="mx-2 mt-1 ">Password:</label>*@
            <input type="password" class="form-control" id="password" name="Password" placeholder="Password">
          </div>       
          </div> 

          <div class="col-md-12 mt-3 p-0">
            <div class="d-flex flex-col ">
          @* <label for="Password" class="mx-2 mt-1 ">Repeat_Password:</label>*@
           <input type="password" class="form-control" id="password" name="Re-Password" placeholder="Repeat_Password">
         </div>       
         </div>

       
        <div class="d-flex justify-content-between w-100 mt-3 ">
        @*     <div class="form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Remember me</label>
                </div>

              *@

          
        </div>
         <div class="w-100" > <button type="submit" name="Submit" class="custombtn px-3 mt-2 ">Register</button></div>

          <a href="Login" class="  mt-3">Login</a>
         
        </form>

        
      </div>

    </div>

  </div>


      </div>
    </div>


    
    
      <!-- <hr class="featurette-divider"> -->
 


    </div>

  </div>
    