MoneyTransfer/Controllers/BankController.cs
using Microsoft.AspNetCore.Mvc;

namespace MoneyTransfer.Controllers
{
    public class BankController : Controller
    {
        public IActionResult Registration()
        {

            return View();
        }
        public IActionResult Login()
        {
            return View();
        }


        //Agent sub field view
        public IActionResult Agent()
        {
            return View();
        }
        public IActionResult Nepalagentlist()
        {
            return View();
        }
        public IActionResult Abroadagentlist()
        {
            return View();
        }
        //


        public IActionResult Currenttransaction()
        {
            return View();
        }
        public IActionResult Newtransaction()
        {
            return View();
        }
        public IActionResult Nepalagent()
        {
            return View();
        }
        public IActionResult Abroadagent()
        {
            return View();
        }

        public IActionResult Homepage()
        {
            return View();
        }

    }
}

MoneyTransfer/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MoneyTransfer.Models;
using System.Diagnostics;

namespace MoneyTransfer.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }


        public IActionResult test()
        {
            return View();
        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MoneyTransfer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
  
 
  <div style="width:100%; height:50px;" class="bg-dark d-flex justify-content-end">
     

      
<div class=" mx-3 pt-3 ">
   <a asp-controller="Bank" asp-action="Login" class="text-white ancor">Login</a>
</div>
<div class="   mx-3 pt-3 ">
   <a asp-controller="Bank" asp-action="Registration" class="text-white ancor">Signup</a>
</div>


    
      
  </div>


<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>